---
- name: set Asia/Seoul timezone
  become: yes
  timezone:
    name: Asia/Seoul

- name: install git
  become: yes
  yum:
    name: git
    # state: latest
    state: present

- name: remove unused yum packages -ntp
  become: yes
  yum:
    name: ntp
    state: absent

- name: install chrony
  become: yes
  yum:
    name: chrony
    state: latest
  notify:
    - start chronyd

- name: create /usr/agent directory
  become: yes
  file: path=/usr/agent state=directory

- name: Install system updates for centos systems
  yum:
    name: '*'
    state: latest
    update_cache: yes

